# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tabitha Frahm
email: tabitha.frahm@gmail.com

#write html inside the double quotes to display in jumbotron
description: "<h3>From Catscratch to Coding:</h3><h1>Yer a Wizard, Tabby!</h1><h3>My Journey to the Center of the Web"


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tfrahm.github.io" # the base hostname & protocol for your site
twitter_username: TabithaFrahm
github_username:  tfrahm

# Build settings
markdown: kramdown
